### ISSUE TITLE
java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by jan-kir-wwu** [Drawethree/spigot-hibernate-demo#1]
Greetings,

I tested your example plugin on my Java 17 Spigot Server as I am really interested in using Hibernate and got the following error:

(see attached picture)
![image](https://user-images.githubusercontent.com/56630012/172016475-4146fdc8-79bf-4b6f-b336-af35379cb07d.png)

Is this resource still up to date or are there any prerequisites missing, which are not on the Github Readme.md?

I hope it is okay to ask that here.
Best regards.

**Comment by jan-kir-wwu** [comment]
Resolved. Its not yet working for Java 17.

**Comment by weihao** [comment]
How did you resolve it?
